name: Tame CODEOWNERS pings

on:
  pull_request:
    types: [converted_to_draft, ready_for_review]

permissions:
  pull-requests: write

jobs:
  on-convert-to-draft:
    if: github.event.action == 'converted_to_draft'
    runs-on: ubuntu-latest
    steps:
      - name: Clear requested reviewers on convert-to-draft
        if: github.event.action == 'converted_to_draft'
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const number = context.payload.pull_request.number;
            const rr = await github.rest.pulls.listRequestedReviewers({owner, repo, pull_number: number});
            const users = rr.data.users.map(u => u.login);
            const teams = rr.data.teams.map(t => t.slug);
            console.log(users);
            console.log(teams);
            if (users.length || teams.length) {
              await github.rest.pulls.removeRequestedReviewers({
                owner, repo, pull_number: number,
                reviewers: users,
                team_reviewers: teams
              });
            }

